# Generated by Django 3.0.4 on 2020-03-13 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ChondoKotha', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='district',
            old_name='division_id',
            new_name='division',
        ),
    ]
